### ISSUE TITLE
Don't send email from Travis

### ISSUE THREAD

**Issue by aantron** [ncthbrt/reconstruct#1]
Because of these lines in `.travis.yml`:

https://github.com/ncthbrt/reconstruct/blob/976c61fd3b8c9bc55bde8dbcfa321a733f5f1c95/.travis.yml#L13-L18

Travis will send me an email after every build :p I suggest to remove them :)

**Comment by ncthbrt** [comment]
Oh lol. Sorry about that. Copied some of your boilerplate

**Comment by grosser** [comment]
can close now :)
